<a href="https://colab.research.google.com/github/Muhdhammad/deep-learning/blob/main/neural-network/simple_nn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

In [ ]:
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, features):

    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [ ]:
features = torch.rand(10, 5)

model = Model(features.shape[1])

model(features)

tensor([[0.3885],
        [0.4014],
        [0.3779],
        [0.4182],
        [0.3813],
        [0.3304],
        [0.3727],
        [0.3678],
        [0.3413],
        [0.3507]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear1.weight

Parameter containing:
tensor([[ 0.3155,  0.3563,  0.0637,  0.0972,  0.2354],
        [-0.2723,  0.3573,  0.2814,  0.4007, -0.4140],
        [ 0.1323,  0.3722, -0.0686, -0.0292,  0.2909]], requires_grad=True)

In [ ]:
model.linear2.weight

Parameter containing:
tensor([[-0.4511, -0.3702, -0.4263]], requires_grad=True)

In [ ]:
model.linear1.bias

Parameter containing:
tensor([-0.2374, -0.3417, -0.1121], requires_grad=True)

In [ ]:
model.linear2.bias

Parameter containing:
tensor([-0.2947], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary

summary(model, input_size=(20, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [20, 1]                   --
├─Linear: 1-1                            [20, 3]                   18
├─ReLU: 1-2                              [20, 3]                   --
├─Linear: 1-3                            [20, 1]                   4
├─Sigmoid: 1-4                           [20, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

- The same neural network with sequential container

In [ ]:
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )


  def forward(self, features):

    out = self.network(features)

    return out

In [ ]:
features = torch.rand(10, 5)

model = Model(features.shape[1])

model(features)

tensor([[0.4602],
        [0.4599],
        [0.4580],
        [0.4580],
        [0.4626],
        [0.4607],
        [0.4659],
        [0.4444],
        [0.4579],
        [0.4654]], grad_fn=<SigmoidBackward0>)