<a href="https://colab.research.google.com/github/Muhdhammad/deep-learning/blob/main/tensors/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

- Reshaping

In [ ]:
tensor1 = torch.arange(10)
tensor1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Reshaped

reshaped1 = tensor1.reshape(2, 5)
reshaped1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
tensor2 = torch.arange(15)
tensor2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# Reshape if we don't know number of elements using -1

reshaped2 = tensor2.reshape(3, -1)
reshaped2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [ ]:
reshaped3 = tensor2.reshape(-1, 5)
reshaped3

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [ ]:
tensor4 = torch.arange(10)
tensor4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# using view

reshaped4 = tensor4.view(2, 5)
reshaped4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# If we update any tensor, the change will be reflected in reshaped tensor also

tensor4[0] = 99
tensor4

tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
reshaped4   # We can see it is also changed here

tensor([[99,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

- Slicing

In [ ]:
tensor = torch.tensor(([1 ,2, 3, 4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12],
                       [13, 14, 15, 16]))
tensor

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

In [ ]:
slice_tensor = tensor[:2, :2]   # first 2 rows and 2 columns
slice_tensor

tensor([[1, 2],
        [5, 6]])

In [ ]:
# Slicing specific rows and columns

slice_tensor = tensor[1:3, [0, 3]]  # rows 1 and 2 and we explicitly select columns at index 0 and 3
slice_tensor

tensor([[ 5,  8],
        [ 9, 12]])

In [ ]:
slice_tensor = tensor[2:4, [1, 2, 3]]  # rows 2 and 3, and columns 1, 2, 3
slice_tensor

tensor([[10, 11, 12],
        [14, 15, 16]])