<a href="https://colab.research.google.com/github/Muhdhammad/deep-learning/blob/main/tensors/tensor_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tensors**

Tensors are multi-dimensional arrays, similar to Numpy arrays but with added capabilities for GPU acceleration.

In [ ]:
import torch
import numpy as np

In [ ]:
x = torch.rand(2, 3) # 2d tensor with 2 rows and 3 columns
x

tensor([[0.0069, 0.9924, 0.5986],
        [0.3698, 0.9819, 0.9726]])

In [ ]:
y = torch.zeros(2, 3, 4)       # 3d tensor with 2 arrays, each having 3 rows and 4 columns
y

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
y.dtype

torch.float32

In [ ]:
y.shape

torch.Size([2, 3, 4])

In [ ]:
# Numpy array

np1 = np.random.rand(2, 3)
np1

array([[0.12615186, 0.46344863, 0.41032029],
       [0.71626942, 0.87254545, 0.06515807]])

In [ ]:
# Create tensor with numpy array

tensor = torch.tensor(np1)
tensor

tensor([[0.1262, 0.4634, 0.4103],
        [0.7163, 0.8725, 0.0652]], dtype=torch.float64)

In [ ]:
# Create tensor with list

my_list = [1, 2, 3, 4, 5]

tensor_list = torch.tensor(my_list)
tensor_list

tensor([1, 2, 3, 4, 5])

In [ ]:
# Accessing elements in tensor

my_tensor = torch.tensor([[2, 5, 7], [1, 6, 9]])
my_tensor[1, 1]

tensor(6)

In [ ]:
# Modifying elements in tensor

tensor_ones = torch.ones(3, 4)
tensor_ones[2, 3] = 5

tensor_ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 5.]])

In [ ]:
# Concatenation

tensor1 = torch.rand(2, 3)
tensor2 = torch.rand(2, 3)

concat_tensor = torch.cat((tensor1, tensor2))
concat_tensor

tensor([[0.3124, 0.0642, 0.8112],
        [0.7253, 0.9613, 0.7850],
        [0.9253, 0.6565, 0.4306],
        [0.2794, 0.1989, 0.7051]])